# Generated by Django 3.2.4 on 2021-06-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('specname', models.CharField(max_length=30, unique=True, verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Справочник специализаций',
                'db_table': 'specialization',
                'ordering': ['specname'],
                'managed': True,
            },
        ),
    ]
