# Generated by Django 3.2.4 on 2021-06-25 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_specialization_specname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'managed': False, 'ordering': ['specname'], 'verbose_name': 'Специализация', 'verbose_name_plural': 'Справочник специализаций'},
        ),
    ]
