# Generated by Django 3.2.4 on 2021-06-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_doctor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('familyname', 'firstname', 'lastname', 'specname')},
        ),
    ]
