# Generated by Django 3.2.4 on 2021-06-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_alter_doctor_lastname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': False, 'ordering': ('familyname', 'firstname', 'lastname', 'specname'), 'verbose_name': 'Врач', 'verbose_name_plural': 'Справочник сотрудников'},
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dapp', models.DateField(verbose_name='День приема')),
                ('appbegin', models.TimeField(verbose_name='Начало')),
                ('append', models.TimeField(verbose_name='Окончание')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registry.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name_plural': 'Расписание',
                'db_table': 'appointment',
                'managed': True,
                'unique_together': {('dapp', 'doctor')},
            },
        ),
    ]
