# Generated by Django 3.2.4 on 2021-06-28 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_auto_20210629_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='specname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registry.specialization', verbose_name='Специализация'),
        ),
    ]
