# Generated by Django 3.2.4 on 2021-06-29 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_appointment_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='room',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кабинет'),
        ),
    ]
