# Generated by Django 3.2.4 on 2021-06-29 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_alter_appointment_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'managed': True, 'ordering': ('dapp', 'specname', 'doctor'), 'verbose_name_plural': 'Расписание приема'},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('dapp', 'specname', 'doctor')},
        ),
        migrations.AlterIndexTogether(
            name='appointment',
            index_together={('dapp', 'specname', 'doctor')},
        ),
    ]
