# Generated by Django 3.2.4 on 2021-06-29 05:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_alter_appointment_dapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dapp',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2021, 6, 30))], verbose_name='День приема'),
        ),
    ]
