# Generated by Django 3.2.4 on 2021-06-30 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_auto_20210630_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'managed': True, 'ordering': ('dapp', 'specname', 'doctor'), 'verbose_name': 'Строка расписания', 'verbose_name_plural': 'Расписание приема'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appbegin',
            field=models.TimeField(choices=[(datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00')], verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='append',
            field=models.TimeField(choices=[(datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00')], verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dapp',
            field=models.DateField(verbose_name='День приема'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='planbudget',
            field=models.PositiveSmallIntegerField(verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='plancommerce',
            field=models.PositiveSmallIntegerField(verbose_name='Внебюджет'),
        ),
    ]
