# Generated by Django 3.2.5 on 2021-07-01 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_auto_20210630_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='planbudget',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Бюджет'),
        ),
    ]
