# Generated by Django 3.2.5 on 2021-07-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0020_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'managed': False, 'ordering': ('-dapp', 'specname', 'doctor'), 'verbose_name': 'Строка расписания', 'verbose_name_plural': 'Расписание приема'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
