# Generated by Django 3.2.5 on 2021-07-04 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_auto_20210703_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True, 'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lastname',
            new_name='patronymic',
        ),
    ]
