# Generated by Django 3.2.5 on 2021-07-04 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0022_auto_20210704_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'managed': True, 'ordering': ('-dapp', 'specname', 'doctor'), 'verbose_name': 'Строка расписания', 'verbose_name_plural': 'Расписание приема'},
        ),
    ]
