# Generated by Django 3.2.5 on 2021-07-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0023_alter_appointment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_slots',
            field=models.BooleanField(default=False),
        ),
    ]
