# Generated by Django 3.2.5 on 2021-07-05 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0026_auto_20210705_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slot', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registry.appointment', verbose_name='Расписание')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'Талон',
                'verbose_name_plural': 'Бронирование',
                'db_table': 'booking',
                'managed': True,
            },
        ),
    ]
