# Generated by Django 3.2.5 on 2021-07-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0027_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': True, 'ordering': ('familyname', 'firstname', 'lastname', 'specname'), 'verbose_name': 'Врач', 'verbose_name_plural': 'Справочник сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'managed': True, 'ordering': ['specname'], 'verbose_name': 'Специализация', 'verbose_name_plural': 'Справочник специализаций'},
        ),
    ]
