# Generated by Django 3.2.5 on 2021-07-10 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0029_alter_booking_index_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'managed': True, 'ordering': ('appointment', 'slot'), 'verbose_name': 'Талон', 'verbose_name_plural': 'Бронирование'},
        ),
    ]
