# Generated by Django 3.2.5 on 2021-08-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0033_auto_20210812_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
