# Generated by Django 3.2.5 on 2021-08-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0037_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
