# Generated by Django 3.2.5 on 2021-08-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0041_alter_appointment_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
