# Generated by Django 3.2.5 on 2021-08-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0042_delete_doctor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('appointment', 'person'), name='unique_appointment_person_person_is_not_null'),
        ),
    ]
