# Generated by Django 4.0.6 on 2022-07-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0043_booking_unique_appointment_person_person_is_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_slots',
            field=models.BooleanField(default=False, verbose_name='Талоны'),
        ),
    ]
